# Generated by Django 4.1.7 on 2023-03-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cod_finca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nombre_finca',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
